### ISSUE TITLE
AttributeError: 'EmbClient' object has no attribute 'set_partition_book'

### ISSUE THREAD

**Issue by xiyaAZ** [txsun1997/CoLAKE#7]
嗨
在 运行 run_pretrain.sh 脚本时报错:
model init
loaded pretrained relation embeddings. dim: 768
starting to initialize senser
sender initialized successfully.
client is initialized successfully.
1 clients connected!
KVStore service 0 start successfully! Listen for request ...
KVClient 0 connect to kvstore successfully!
Traceback (most recent call last):
  File "/home/ktfp768/CoLAKE/pretrain/run_pretrain.py", line 267, in <module>
    train()
  File "/home/ktfp768/CoLAKE/pretrain/run_pretrain.py", line 199, in train
    cache_dir=PYTORCH_PRETRAINED_BERT_CACHE + '/dist_{}'.format(args.local_rank))
  File "/home/ktfp768/test/lib/python3.6/site-packages/transformers/modeling_utils.py", line 655, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "../pretrain/model.py", line 21, in __init__
    self.ent_embeddings = LargeEmbedding(ip_config, emb_name, ent_lr, num_ent)
  File "../pretrain/large_emb.py", line 195, in __init__
    self.client.set_partition_book(emb_name, torch.zeros(num_emb))
AttributeError: 'EmbClient' object has no attribute 'set_partition_book'
Exit KVStore service 0, solved message count: 4
server is started.

self.client 是一个初始化之后的EmbClient，继承于KVClient，确实没有set_partition_book这个方法。看了下dgl包，只有KVserver有set_partition_notebook()
把LargeEmbedding里面这一行改掉之后，模型报错:KeyError: 'entity_emb-part-'

**Comment by txsun1997** [comment]
DGL版本请使用0.4.3
`pip install dgl==0.4.3`

**Comment by xiyaAZ** [comment]
换成0.4.3之后报错:
model init
loaded pretrained relation embeddings. dim: 768
Traceback (most recent call last):
  File "/home/ktfp768/CoLAKE/pretrain/run_pretrain.py", line 266, in <module>
    train()
  File "/home/ktfp768/CoLAKE/pretrain/run_pretrain.py", line 198, in train
    cache_dir=PYTORCH_PRETRAINED_BERT_CACHE + '/dist_{}'.format(args.local_rank))
  File "/home/ktfp768/test/lib/python3.6/site-packages/transformers/modeling_utils.py", line 655, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "../pretrain/model.py", line 20, in __init__
    self.ent_embeddings = LargeEmbedding(ip_config, emb_name, ent_lr, num_ent)
  File "../pretrain/large_emb.py", line 185, in __init__
    self.client = EmbClient(server_namebook)
  File "../pretrain/large_emb.py", line 99, in __init__
    super().__init__(server_namebook, queue_size, net_type)
  File "/home/ktfp768/test/lib/python3.6/site-packages/dgl/contrib/dis_kvstore.py", line 588, in __init__
    self._machine_id = self._get_local_machine_id()
  File "/home/ktfp768/test/lib/python3.6/site-packages/dgl/contrib/dis_kvstore.py", line 981, in _get_local_machine_id
    if ip in self._local_ip4_addr_list():
  File "/home/ktfp768/test/lib/python3.6/site-packages/dgl/contrib/dis_kvstore.py", line 999, in _local_ip4_addr_list
    struct.pack('256s', name[:15].encode("UTF-8")))[20:24])
OSError: [Errno 99] Cannot assign requested address
Exception ignored in: <bound method KVClient.__del__ of <pretrain.large_emb.EmbClient object at 0x7faf4ea9ed68>>
Traceback (most recent call last):
  File "/home/ktfp768/test/lib/python3.6/site-packages/dgl/contrib/dis_kvstore.py", line 604, in __del__
    _finalize_sender(self._sender)
AttributeError: 'EmbClient' object has no attribute '_sender'
Exception ignored in: <bound method LargeEmbedding.__del__ of LargeEmbedding()>
Traceback (most recent call last):
  File "../pretrain/large_emb.py", line 204, in __del__
    self.client.shut_down()
  File "/home/ktfp768/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'LargeEmbedding' object has no attribute 'client'
Traceback (most recent call last):
  File "/opt/scp/software/Python/3.6.3-foss-2017a/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/scp/software/Python/3.6.3-foss-2017a/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ktfp768/test/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ktfp768/test/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ktfp768/test/bin/python', '-u', '/home/ktfp768/CoLAKE/pretrain/run_pretrain.py', '--local_rank=0', '--name', 'CoLAKE', '--data_prop', '1.0', '--batch_size', '2048', '--lr', '1e-4', '--ent_lr', '1e-4', '--epoch', '1', '--grad_accumulation', '16', '--save_model', '--emb_name', 'entity_emb', '--n_negs', '200', '--beta', '0.98']' returned non-zero exit status 1.


****
已解决，方法如下
重写KVClient中的def _get_local_machine_id(self):
读取namebook，返回当前的machine_id
